apis:
  api_delay_seconds: 2
  elevenlabs:
    default_voice: 21m00Tcm4TlvDq8ikWAM
    timeout: 20
  gemini:
    max_frames: 20
    model_id: gemini-2.0-flash
    safety_threshold: medium
    timeout: 30
  youtube:
    api_service_name: youtube
    api_version: v3
    scopes:
    - https://www.googleapis.com/auth/youtube.upload
    - https://www.googleapis.com/auth/youtube.force-ssl
    - https://www.googleapis.com/auth/youtubepartner
    self_certification: true
    upload_category_id: '24'
    upload_privacy_status: public
audio:
  audio_normalization_enabled: true
  background_music_enabled: true
  background_music_narrative_volume_factor: 0.2
  background_music_volume: 0.06
  loudness_normalization_lufs: -16.0
  music_categories:
    emotional:
    - sad
    - heartwarming
    - touching
    - sentimental
    funny:
    - quirky
    - comedic
    - playful
    - lighthearted
    informative:
    - neutral
    - documentary
    - educational
    - background
    relaxing:
    - calm
    - peaceful
    - ambient
    - soothing
    suspenseful:
    - tense
    - dramatic
    - action
    - exciting
    - intense
    upbeat:
    - energetic
    - positive
    - happy
    - uplifting
    - funk
    - beat
  music_fade_in_duration: 1.0
  music_fade_out_duration: 1.0
  narrative_delay_after_hook: 0.5
  original_audio_mix_volume: 0.15
  peak_limiting_threshold: -1.0
  preserve_natural_sounds: true
  sound_effect_types:
    dramatic_sounds:
    - boom
    - thunder
    - rumble
    - tension
    impact_sounds:
    - impact
    - hit
    - thud
    - bang
    - crash
    - smash
    liquid_sounds:
    - splash
    - pour
    - glug
    - water
    - liquid
    mechanical_sounds:
    - click
    - pop
    - snap
    - tick
    - beep
    notification_sounds:
    - ding
    - chime
    - bell
    - alert
    - notification
    transition_sounds:
    - whoosh
    - swoosh
    - zip
    - swish
    - wind
  sound_effects_enabled: true
  sound_effects_fade_duration: 0.08
  sound_effects_volume: 0.7
  sound_effects_volume_multiplier: 1.2
  tts_emotional_volume_boost: 0.15
  tts_volume: 0.85
content:
  curated_subreddits:
  - oddlysatisfying
  - nextfuckinglevel
  - BeAmazed
  - woahdude
  - MadeMeSmile
  - Eyebleach
  - interestingasfuck
  - Damnthatsinteresting
  - AnimalsBeingBros
  - HumansBeingBros
  - wholesomememes
  - ContagiousLaughter
  - foodporn
  - CookingVideos
  - ArtisanVideos
  - educationalgifs
  - DIY
  - gardening
  - science
  - space
  - NatureIsCool
  - aww
  - AnimalsBeingDerps
  - rarepuppers
  - LifeProTips
  - GetMotivated
  - toptalent
  - BetterEveryLoop
  - childrenfallingover
  - instantregret
  - wholesomegifs
  - Unexpected
  - nevertellmetheodds
  - whatcouldgoright
  - holdmymilk
  - maybemaybemaybe
  - mildlyinteresting
  forbidden_words:
  - fuck
  - fucking
  - fucked
  - fuckin
  - shit
  - shitty
  - shitting
  - wtf
  - stfu
  - omfg
  - porn
  - pornographic
  - nsfw
  - xxx
  - sex
  - sexual
  - nude
  - naked
  - racist
  - racism
  - nazi
  - sexist
  max_reddit_posts_to_fetch: 10
  monetization_tags:
  - family friendly
  - educational
  - informative
  - wholesome
  - positive
  - interesting
  - amazing
  - satisfying
  - relaxing
  - shorts
  - shortvideo
  unsuitable_content_types:
  - violence
  - violent
  - gore
  - blood
  - death
  - killing
  - murder
  - weapon
  - gun
  - knife
  - drug
  - drugs
  - cocaine
  - heroin
  - marijuana
  - weed
  - smoking
  - alcohol
  - drunk
  - gambling
  - casino
  - bet
  - betting
  - political
  - politics
  - election
  - trump
  - biden
  - religion
  - religious
  - god
  - jesus
  - muslim
  - christian
  - church
  - mosque
  - suicide
  - depression
  - self-harm
  - cutting
  - mental health crisis
  - accident
  - crash
  - injury
  - hospital
  - medical emergency
  - conspiracy
  - fake news
  - misinformation
  - hoax
  - adult content
  - mature content
  - 18+
  - nsfw
  - not safe for work
development:
  enable_debug_mode: false
  max_test_videos: 3
  mock_ai_analysis: false
  mock_youtube_upload: false
  save_intermediate_files: false
  test_subreddits:
  - test
  - videos
effects:
  color_grade_enabled: true
  color_grade_intensity: 0.7
  enable_audio_crossfade: true
  enable_seamless_looping: true
  loop_compatibility_threshold: 0.3
  loop_crossfade_duration: 0.3
  loop_extend_mode: middle_repeat
  loop_sample_duration: 0.5
  loop_target_duration: null
  loop_trim_from_center: true
  max_zoom: 1.08
  shake_intensity: 0.02
  stabilization_threshold: 5.0
  subtle_zoom_enabled: true
enhancement_optimization:
  last_updated: '2025-06-08T09:19:31.227471'
  optimal_parameters:
    sound_effects:
      density_threshold: 0.25
      fade_duration: 0.08
      volume_multiplier: 1.2
    text_overlays:
      animation_speed: 1.0
      display_duration: 2.5
      font_size_multiplier: 1.0
    visual_effects:
      color_grade_intensity: 0.7
      transition_duration: 0.3
      zoom_intensity: 1.08
fallbacks:
  default_analysis:
    emotional_keywords:
    - interesting
    - engaging
    has_clear_narrative: false
    hook_text: Watch this amazing moment!
    mood: exciting
    music_genres:
    - upbeat
    original_audio_is_key: true
    suggested_title: Amazing Reddit Video
    summary_for_description: Check out this incredible content from Reddit!
  default_hashtags:
  - '#viral'
  - '#shorts'
  - '#reddit'
  default_mood: exciting
  enable_basic_effects: true
logging:
  backup_count: 5
  component_levels:
    src.database.db_manager: WARNING
    src.integrations.ai_client: INFO
    src.integrations.reddit_client: INFO
    src.integrations.youtube_client: INFO
    src.processing.video_processor: INFO
  enable_file_logging: true
  level: INFO
  log_file: video_generation.log
  max_log_size_mb: 10
processing:
  cleanup_after_upload: true
  enable_cleanup: true
  keep_successful_videos: false
  max_temp_files: 50
  temp_dir: temp_processing
text_overlay:
  animation: fade
  default_duration: 2.5
  fade_in: 0.2
  fade_out: 0.2
  font_size_multiplier: 1.0
  font_size_ratio_profiles:
    long: 0.035
    medium: 0.045
    short: 0.06
  graphical_bg_color: rgba(0,0,0,0.5)
  graphical_font: Montserrat-Bold.ttf
  graphical_font_size_ratio: 0.056
  graphical_stroke_color: black
  graphical_stroke_width: 2
  graphical_text_color: white
  subtitle_bg_color: rgba(0,0,0,0.4)
  subtitle_font: Montserrat-Regular.ttf
  subtitle_font_size_ratio: 0.04
  subtitle_position:
  - center
  - 0.92
  subtitle_stroke_color: black
  subtitle_stroke_width: 1
  subtitle_text_color: white
video:
  audio_bitrate: 256k
  audio_codec: aac
  chunk_size: 30
  default_audio_fps: 44100
  default_crop:
  - 0.25
  - 0.25
  - 0.75
  - 0.75
  ffmpeg_cpu_preset: slow
  ffmpeg_cq_gpu: '20'
  ffmpeg_crf_cpu: '20'
  ffmpeg_gpu_preset: p6
  loudness_target_lufs: -14.0
  max_memory_usage: 0.8
  max_retries: 3
  target_aspect_ratio: 0.5625
  target_duration: 59
  target_fps: 30
  target_resolution:
  - 1080
  - 1920
  video_bitrate_high: 15M
  video_codec_cpu: libx264
  video_codec_gpu: h264_nvenc
  video_quality_profile: high
