ai_features:
  enable_ab_testing: true
  enable_advanced_audio: true
  enable_cinematic_editing: true
  fallback_confidence_threshold: 0.6
  use_fallback_analysis: true

api:
  gemini_api_key: your_gemini_api_key
  gemini_model: gemini-2.0-flash
  gemini_rate_limit_daily: 500
  gemini_rate_limit_rpm: 10
  reddit_client_id: your_reddit_client_id
  reddit_client_secret: your_reddit_client_secret
  reddit_user_agent: YouTubeShorts:v2.0:enhanced (by u/yourusername)
  youtube_api_key: your_youtube_api_key
  youtube_client_secrets_file: youtube_credentials.json
  
  # TikTok API Configuration
  tiktok_api_key: your_tiktok_api_key
  tiktok_api_secret: your_tiktok_api_secret
  tiktok_access_token: your_tiktok_access_token
  tiktok_refresh_token: your_tiktok_refresh_token
  tiktok_client_key: your_tiktok_client_key
  tiktok_rate_limit_requests: 100
  tiktok_rate_limit_window: 3600
  
  # Instagram API Configuration
  instagram_username: your_instagram_username
  instagram_password: your_instagram_password
  instagram_session_id: your_instagram_session_id
  instagram_access_token: your_instagram_access_token
  instagram_client_id: your_instagram_client_id
  instagram_client_secret: your_instagram_client_secret
  instagram_rate_limit_requests: 50
  instagram_rate_limit_window: 3600

spotify:
  client_id: your_spotify_client_id
  client_secret: your_spotify_client_secret
  enable_music_downloads: true
  download_quality: high
  max_tracks_per_search: 50
  preferred_genres:
    - electronic
    - pop
    - rock
    - indie
    - instrumental

audio:
  audio_enhancement:
    enable_limiter: true
    enable_noise_gate: true
    limiter_threshold: -2
    noise_gate_threshold: -40
  background_music:
    enable: true
    fade_in_duration: 2.0
    fade_out_duration: 2.0
    loop_if_short: true
    volume: 0.4
  sound_effects:
    apply_reverb: false
    enable: true
    normalize_levels: true
    volume: 0.7

audio_processing:
  clarity_boost: 0.2
  compression_ratio: 0.4
  duck_during_narration: true
  duck_volume: 0.3
  enable_smart_ducking: true
  enable_voice_enhancement: true
  fade_duration: 0.5
  music_analysis_window: 2048
  noise_reduction_strength: 0.3
  preserve_music_dynamics: true
  sample_rate: 44100
  smart_detection: true
  voice_frequency_range: [80, 8000]

cinematic_editing:
  composition_analysis: true
  contrast_weight: 0.3
  enable_cinematic_transitions: true
  enable_dynamic_movements: true
  leading_lines_weight: 0.2
  max_zoom_factor: 1.8
  min_scene_duration: 2.0
  motion_threshold: 0.3
  movement_intensity_range: [0.3, 1.5]
  rule_of_thirds_weight: 0.3
  symmetry_weight: 0.2
  transition_duration_range: [0.5, 1.5]
  visual_complexity_weight: 0.4

database:
  ab_test_retention_days: 30
  cleanup_interval_hours: 24
  metrics_retention_days: 90
  sqlite_db_path: data/youtube_shorts.db

development:
  debug_mode: false
  enable_profiling: false
  mock_api_calls: false
  save_intermediate_files: false
  skip_upload_in_test_mode: true
  test_video_duration_limit: 60
  use_sample_data: false

feature_flags:
  enable_advanced_analytics: true
  enable_auto_captions: true
  enable_auto_publishing: false
  enable_experimental_ai: false
  enable_real_time_monitoring: true
  enable_cross_platform_upload: true
  enable_social_media_analytics: true

# Social Media Configuration
social_media:
  # Cross-platform upload settings
  enable_cross_posting: true
  cross_post_delay: 300  # 5 minutes between platform posts
  
  # Platform-specific settings
  youtube:
    enable_auto_upload: true
    default_visibility: "public"
    enable_auto_captions: true
    enable_auto_thumbnails: true
  
  tiktok:
    enable_auto_upload: true
    default_visibility: "public"
    enable_auto_hashtags: true
    enable_trending_topics: true
  
  instagram:
    enable_auto_upload: true
    default_media_type: "reel"  # reel, post, story
    enable_auto_captions: true
    enable_location_tags: false
  
  # Optimal posting times (24-hour format)
  optimal_timing:
    youtube:
      best_days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
      best_hours: [12, 15, 19, 21]
      timezone: "UTC"
    
    tiktok:
      best_days: ["Tuesday", "Thursday", "Friday", "Saturday"]
      best_hours: [9, 12, 19, 21]
      timezone: "UTC"
    
    instagram:
      best_days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
      best_hours: [11, 13, 15, 19]
      timezone: "UTC"
  enable_style_transfer: false
  enable_voice_cloning: false

logging:
  backup_count: 5
  component_levels:
    ai_client: DEBUG
    audio_processor: INFO
    channel_manager: INFO
    cinematic_editor: INFO
    enhancement_optimizer: INFO
    thumbnail_generator: INFO
  console_logging: true
  file_logging: true
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  log_rotation: true
  max_log_size_mb: 10

paths:
  ab_test_results_dir: ab_test_results
  ai_models_cache_dir: ai_models_cache
  base_dir: .
  downloads_dir: downloads
  fonts_dir: fonts
  logs_dir: logs
  music_dir: music
  processed_dir: processed
  sound_effects_dir: sound_effects
  temp_dir: temp
  thumbnails_dir: thumbnails

performance:
  aggressive_memory_cleanup: true
  chunk_size_mb: 100
  clear_cache_between_videos: true
  enable_gpu_acceleration: true
  gpu_memory_management: true
  max_concurrent_videos: 3
  max_vram_usage: 0.7
  memory_monitoring_interval: 30

tts:
  azure:
    pitch: medium
    speaking_rate: medium
    voice_name: en-US-AriaNeural
  edge_tts:
    pitch: +0Hz
    rate: +0%
    voice: en-US-AriaNeural
  elevenlabs:
    enable_voice_enhancement: true
    model_id: eleven_monolingual_v1
    voice_id: 21m00Tcm4TlvDq8ikWAM
    voice_similarity_boost: 0.75
    voice_stability: 0.75
  primary_service: elevenlabs

video_processing:
  audio_bitrate: 128k
  audio_codec: aac
  default_output_resolution: [1080, 1920]
  enable_auto_color_grading: true
  enable_dynamic_zoom: true
  enable_motion_blur_compensation: true
  enable_speed_optimization: true
  enable_speed_ramping: true
  max_file_size_mb: 500
  max_video_duration: 600
  min_video_duration: 5
  pixel_format: yuv420p
  speed_optimization_level: aggressive
  target_fps: 30
  video_bitrate: 5M
  video_codec: libx264
  video_quality_profile: speed

youtube:
  add_performance_hashtags: true
  auto_generate_description: true
  default_category: '22'
  default_privacy: public
  enable_comments: true
  enable_ratings: true
  include_enhancement_credits: true
  thumbnail_quality: 95
  upload_retry_count: 3
  upload_timeout_minutes: 10
