# Video Processing Configuration
video:
  target_duration: 60
  target_resolution: [1080, 1920]
  max_retries: 3
  default_crop: [0.25, 0.25, 0.75, 0.75]

text_overlay:
  font: Impact
  font_size_ratio: 0.08
  stroke_width: 3
  position: [0.5, 0.85]

effects:
  shake_intensity: 0.02
  max_zoom: 1.1
  stabilization_threshold: 5.0
  color_grade_intensity: 0.7
processing:
  temp_dir: /content/temp

apis:
  gemini:
    max_frames: 20
    timeout: 30
    safety_threshold: medium
  elevenlabs:
    timeout: 20
    default_voice: 21m00Tcm4TlvDq8ikWAM

subreddits:
  - CrazyFuckingVideos
  - funny
  - videos
  - interestingasfuck
  - mildlyinteresting
  - mildlyinfuriating
  - CasualUK
  - BeAmazed
  - cats
  - Damnthatsinteresting
  - chaoticgood

fallbacks:
  enable_basic_effects: true
  default_mood: exciting
  default_hashtags: ['#viral', '#shorts', '#reddit']

subtitles:
  font_size_ratio_profiles:
    short: 0.06
    medium: 0.045
    long: 0.035
  font: Montserrat-Regular.ttf
  font_per_language:
    en: Montserrat-Regular.ttf
    th: NotoSansThai-Regular.ttf
  text_color: 'white'
  stroke_color: 'black'
  stroke_width: 1
  bg_style: box  # box, outline, dynamic
  bg_opacity: 0.4
  position: bottom_center  # bottom_center, top_center, custom
  y_offset: 0.92  # relative vertical offset (0.92 = bottom 8%)
  fade_in: 0.2
  fade_out: 0.2
  animation: fade  # fade, none

looping:
  enable: true
  crossfade_duration: 0.3
  compatibility_threshold: 0.3
  extend_mode: middle_repeat  # middle_repeat, slow_motion, boomerang, ai_transition, none
  visual_masking: false  # true to enable masking at loop point
  masking_effect: fade_black  # fade_black, blur, overlay, none
  masking_duration: 0.15
  content_aware: false  # true to enable content-aware loop points